export const COFFEE_ITEMS = [
  { name: "Американо", unitPrice: 36, longTitle: false },
  { name: "Американо з молоком", unitPrice: 40, longTitle: true },
  { name: "Американо", unitPrice: 41, longTitle: false },
  { name: "Американо з молоком", unitPrice: 45, longTitle: true },
  { name: "Еспресо", unitPrice: 36, longTitle: false },
  { name: "Еспресо з молоком", unitPrice: 40, longTitle: true },
  { name: "Еспресо", unitPrice: 41, longTitle: false },
  { name: "Еспресо з молоком", unitPrice: 45, longTitle: true },
  { name: "Капучино", unitPrice: 57, longTitle: false },
  { name: "Капучино", unitPrice: 62, longTitle: false },
  { name: "Латте", unitPrice: 57, longTitle: false },
  { name: "Латте", unitPrice: 52, longTitle: false },
  { name: "Лунго", unitPrice: 36, longTitle: false },
  { name: "Лунго", unitPrice: 41, longTitle: false },
  { name: "Допіо", unitPrice: 70, longTitle: false },
  { name: "Допіо", unitPrice: 80, longTitle: false },
  { name: "Бамбл (Джміль)", unitPrice: 65, longTitle: true },
  { name: "Айс латте", unitPrice: 61, longTitle: false },
  { name: "Раф ср.", unitPrice: 62, longTitle: false },
  { name: "Раф вел.", unitPrice: 67, longTitle: false },
  { name: "Флет вайт", unitPrice: 80, longTitle: false },
  { name: "Флет вайт", unitPrice: 85, longTitle: false },
  { name: "Капучино сер.", unitPrice: 53, longTitle: false },
  { name: "Гарячий шоколад", unitPrice: 61, longTitle: true },
  { name: "Какао", unitPrice: 36, longTitle: false },
  { name: "Чай заварний", unitPrice: 35, longTitle: false },
  { name: "Чай натуральний", unitPrice: 45, longTitle: true },
  { name: "Айс латте", unitPrice: 63, longTitle: false },
  { name: "Айс латте без/л", unitPrice: 61, longTitle: true },
  { name: "Айс латте без/л", unitPrice: 66, longTitle: true },
  { name: "Еспресо тонік", unitPrice: 82, longTitle: true },
  { name: "Гляссе", unitPrice: 58, longTitle: false },
  { name: "Лимонад", unitPrice: 60, longTitle: false },
  { name: "Мохіто", unitPrice: 60, longTitle: false },
  { name: "Молочний коктейль", unitPrice: 60, longTitle: true },
  { name: "Американо сер.ст. 2 б/л", unitPrice: 51, longTitle: true },
  { name: "Капучино сер. на б/л", unitPrice: 57, longTitle: true },
  { name: "3 в 1", unitPrice: 20, longTitle: false },
  { name: "Розчинна кава", unitPrice: 20, longTitle: true },
  { name: "3 в 1 / розч. кава", unitPrice: 11.5, longTitle: true },
  { name: "Пакетик чая", unitPrice: 17.5, longTitle: false },
  { name: "Стік чаю", unitPrice: 29.0, longTitle: false },
  { name: "Коньяк 0.25", unitPrice: 15.0, longTitle: false },
  { name: "Коньяк 0.50", unitPrice: 30.0, longTitle: false },
  { name: "Коньяк 0.100", unitPrice: 60.0, longTitle: false },
  { name: "Трубочка м", unitPrice: 0.5, longTitle: false },
  { name: "Трубочка в", unitPrice: 1, longTitle: false },
  { name: "Стакан великий", unitPrice: 16.5, longTitle: true },
  { name: "Стакан сер. (роз.)", unitPrice: 16.5, longTitle: true },
  { name: "Стакан американо", unitPrice: 10.5, longTitle: true },
  { name: "Стакан еспресо", unitPrice: 10.5, longTitle: true },
  { name: "Стакан пл. (купол)", unitPrice: 22.0, longTitle: true },
];

export const ITEMS_PER_SLIDE = 8;
export const SYRUP_PRICE = 2;
export const FREE_MILK = 5;
export const CREAM = 5;
export const STORAGE_KEY = "coffee-box-order";
