export const COFFEE_ITEMS = [
  { name: "Американо", unitPrice: 36, longTitle: false },
  { name: "Американо з молоком", unitPrice: 40, longTitle: true },
  { name: "Американо", unitPrice: 41, longTitle: false },
  { name: "Американо з молоком", unitPrice: 45, longTitle: true },
  { name: "Еспресо", unitPrice: 36, longTitle: false },
  { name: "Еспресо з молоком", unitPrice: 40, longTitle: true },
  { name: "Еспресо", unitPrice: 41, longTitle: false },
  { name: "Еспресо з молоком", unitPrice: 45, longTitle: true },
  { name: "Лунго", unitPrice: 36, longTitle: false },
  { name: "Лунго", unitPrice: 41, longTitle: false },
  { name: "Допіо", unitPrice: 70, longTitle: false },
  { name: "Допіо", unitPrice: 80, longTitle: false },
  { name: "Капучино", unitPrice: 52, longTitle: false },
  { name: "Капучино", unitPrice: 57, longTitle: false },
  { name: "Латте", unitPrice: 52, longTitle: false },
  { name: "Латте", unitPrice: 57, longTitle: false },
  { name: "Раф ср.", unitPrice: 57, longTitle: false },
  { name: "Раф вел.", unitPrice: 63, longTitle: false },
  { name: "Флет вайт", unitPrice: 75, longTitle: false },
  { name: "Флет вайт", unitPrice: 80, longTitle: false },
  { name: "Гарячий шоколад", unitPrice: 56, longTitle: true },
  { name: "Какао", unitPrice: 31, longTitle: false },
  { name: "Чай заварний", unitPrice: 30, longTitle: false },
  { name: "Чай натуральний", unitPrice: 39, longTitle: true },
  { name: "Айс латте", unitPrice: 56, longTitle: false },
  { name: "Айс латте", unitPrice: 61, longTitle: false },
  { name: "Айс латте без/л", unitPrice: 58, longTitle: true },
  { name: "Айс латте без/л", unitPrice: 63, longTitle: true },
  { name: "Бамбл (Джміль)", unitPrice: 60, longTitle: true },
  { name: "Еспресо тонік", unitPrice: 76, longTitle: true },
  { name: "Гляссе", unitPrice: 48, longTitle: false },
  { name: "Лимонад", unitPrice: 55, longTitle: false },
  { name: "Мохіто", unitPrice: 55, longTitle: false },
  { name: "Молочний коктейль", unitPrice: 55, longTitle: true },
  { name: "3 в 1", unitPrice: 20, longTitle: false },
  { name: "Розчинна кава", unitPrice: 20, longTitle: true },
  { name: "3 в 1 / розч. кава", unitPrice: 11.5, longTitle: true },
  { name: "Трубочка м", unitPrice: 0.5, longTitle: false },
  { name: "Трубочка в", unitPrice: 1, longTitle: false },
];

export const ITEMS_PER_SLIDE = 8;
export const SYRUP_PRICE = 2;
export const STORAGE_KEY = "coffee-box-order";
