export const COFFEES = [
  {
    name: "Домінікана",
    saturation: 10,
    acidity: 7,
    bitterness: 6,
    strength: 8,
    aroma: 10,
  },
  {
    name: "Бразилія",
    saturation: 8,
    acidity: 6,
    bitterness: 6,
    strength: 6,
    aroma: 6,
  },
  {
    name: "Ефіопія",
    saturation: 5,
    acidity: 7,
    bitterness: 6,
    strength: 6,
    aroma: 7,
  },
  {
    name: "Коста-Ріка",
    saturation: 8,
    acidity: 8,
    bitterness: 6,
    strength: 6,
    aroma: 8,
  },
  {
    name: "Панама",
    saturation: 8,
    acidity: 7,
    bitterness: 6,
    strength: 7,
    aroma: 8,
  },
  {
    name: "Марагонджип",
    saturation: 6,
    acidity: 4,
    bitterness: 8,
    strength: 8,
    aroma: 8,
  },
  {
    name: "Бразилія",
    secondaryName: "(жовтий бурбон)",
    saturation: 8,
    acidity: 6,
    bitterness: 6,
    strength: 6,
    aroma: 9,
    subText: true,
  },
  {
    name: "Колумбія ",
    secondaryName: "(з маскою)",
    saturation: 6,
    acidity: 6,
    bitterness: 6,
    strength: 6,
    aroma: 6,
    subText: true,
  },
  {
    name: "Колумбія",
    secondaryName: "(чаша)",
    saturation: 6,
    acidity: 6,
    bitterness: 6,
    strength: 5,
    aroma: 8,
    subText: true,
  },
  {
    name: "Кенія",
    saturation: 10,
    acidity: 9,
    bitterness: 6,
    strength: 6,
    aroma: 10,
  },
  {
    name: "Гондурас",
    saturation: 7,
    acidity: 5,
    bitterness: 7,
    strength: 6,
    aroma: 6,
  },
  {
    name: "Гватемала",
    saturation: 8,
    acidity: 7,
    bitterness: 3,
    strength: 7,
    aroma: 7,
  },
  {
    name: "В’єтнам",
    saturation: 7,
    acidity: 6,
    bitterness: 6,
    strength: 7,
    aroma: null,
  },
  {
    name: "Індія",
    saturation: 6,
    acidity: 0,
    bitterness: 8,
    strength: 9,
    aroma: null,
  },
  {
    name: "Суматра",
    saturation: 9,
    acidity: 5,
    bitterness: 7,
    strength: 7,
    aroma: 9,
  },
];
